// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2y8a-lXp92FlsR4cSrmWRt99iq8q9Jts',
    appId: '1:1083381547820:web:7ae6a57030de377cf8e289',
    messagingSenderId: '1083381547820',
    projectId: 'mjtechglobal-web',
    authDomain: 'mjtechglobal-web.firebaseapp.com',
    storageBucket: 'mjtechglobal-web.firebasestorage.app',
    measurementId: 'G-LF1QGDNJ3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXn4CL29XVfdGfLOmKKiC9LQSEdkKmv6w',
    appId: '1:1083381547820:android:6f7a1b5d3d88c500f8e289',
    messagingSenderId: '1083381547820',
    projectId: 'mjtechglobal-web',
    storageBucket: 'mjtechglobal-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtX981s8c0lBKsYDIQ6Mr8HZLmwoVZdE',
    appId: '1:1083381547820:ios:3a13846701351fc4f8e289',
    messagingSenderId: '1083381547820',
    projectId: 'mjtechglobal-web',
    storageBucket: 'mjtechglobal-web.firebasestorage.app',
    iosClientId: '1083381547820-pvvn31pjqssqa28ado6qlnpuo7apv559.apps.googleusercontent.com',
    iosBundleId: 'com.mjtech.internship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFtX981s8c0lBKsYDIQ6Mr8HZLmwoVZdE',
    appId: '1:1083381547820:ios:99207e49acaa1c00f8e289',
    messagingSenderId: '1083381547820',
    projectId: 'mjtechglobal-web',
    storageBucket: 'mjtechglobal-web.firebasestorage.app',
    iosClientId: '1083381547820-lela78acp5icilh7q23vm7ltqio1itij.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2y8a-lXp92FlsR4cSrmWRt99iq8q9Jts',
    appId: '1:1083381547820:web:b0a12976d1a39e31f8e289',
    messagingSenderId: '1083381547820',
    projectId: 'mjtechglobal-web',
    authDomain: 'mjtechglobal-web.firebaseapp.com',
    storageBucket: 'mjtechglobal-web.firebasestorage.app',
    measurementId: 'G-SC9S48SER8',
  );
}
